swagger: "2.0"
info:
  title: "Hello world API"
  version: "1.0.1"
  contact:
    email: "oscar.garcia@mariachi.io"
    name: "OGA"
    url: "https://spring.io"
  description: "Api for greeting new Microservices developers"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/apache2.0.html"
  termsOfService: "http://swagger.io"
basePath: "/api"
tags:
  - name: "Hello group"
    description: "Everything about hello world"
    externalDocs:
      url: "http://spring.io"
      description: "Find out more"
schemes:
  - http
  - https
paths:
  /greeting:
    get:
      tags:
        - "Hello group"
      description: "Get all the greeting in the world"
      operationId: "getAllGreetings"
      produces:
        - "application/json"
      responses:
        200:
          description: Success
          schema:
            type: array
            items: 
              $ref: "#/definitions/Greeting"
        404:
          description: Greetings not found
    post:
      parameters:
        - name: greeting
          in: body
          schema:
            $ref: "#/definitions/Greeting"
          required: true
      operationId: addGreeting
      summary: "Api for adding greetings"
      produces:
      - "application/json"
      responses:
        200:
          description: Success
          schema: 
            $ref: "#/definitions/Greeting"      
  /greeting/{message}:
    get:
      tags:
        - "Hello group"
      description: "Get one greeting"
      operationId: "getGreetings"
      produces:
        - "application/json"
      parameters:
        - name: "message"
          in: path
          type: string
          required: true
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/Greeting"
        404:
          description: Greeting not found
definitions:
  Greeting:
    required:
      - "message"
      - "id"
    properties: 
      id:
        type: integer
        format: "int64"
        example: "1234"
        description: "The greeting internal identifier"
      message:
        type: string
        example: "Hello world!!!!!!"
        description: "Greeting to process"
      location:
        type: string
        example: "CDMX"
        description: "Source location of the greeting message"
    