apiVersion: apps/v1
kind: Deployment
metadata:
  name: organization-v2
spec:
  selector:
    matchLabels:
      app: organization
      version: v2
  template:
    metadata:
      labels:
        app: organization
        version: v2
    spec:
      containers:
        - name: organization
          image: containersoga/organization
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mongodb
                  key: database-name
            - name: MONGO_USERNAME 
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: database-user
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: database-password