FROM adoptopenjdk/openjdk11:jdk-11.0.15_10-alpine
VOLUME /tmp
ARG JAVA_OPTS
ENV JAVA_OPTS=$JAVA_OPTS
COPY target/store-0.0.1-SNAPSHOT.jar store.jar
EXPOSE 8082
ENTRYPOINT exec java $JAVA_OPTS -jar store.jar
# For Spring-Boot project, use the entrypoint below to reduce Tomcat startup time.
#ENTRYPOINT exec java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar store.jar
